version: '3.9'

services:
  postgres:
    image: postgres:14.13-alpine3.20
    restart: always
    shm_size: 128mb
    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: cefet
    ports:
      - 5429:5432